// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PostApiV1AvatarsMultipartBody defines parameters for PostApiV1Avatars.
type PostApiV1AvatarsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PostApiV1AvatarsParams defines parameters for PostApiV1Avatars.
type PostApiV1AvatarsParams struct {
	XUserID string `json:"X-User-ID"`
}

// DeleteApiV1AvatarsIdParams defines parameters for DeleteApiV1AvatarsId.
type DeleteApiV1AvatarsIdParams struct {
	XUserID string `json:"X-User-ID"`
}

// GetApiV1AvatarsIdParams defines parameters for GetApiV1AvatarsId.
type GetApiV1AvatarsIdParams struct {
	Size   *string `form:"size,omitempty" json:"size,omitempty"`
	Format *string `form:"format,omitempty" json:"format,omitempty"`
}

// PostApiV1AvatarsMultipartRequestBody defines body for PostApiV1Avatars for multipart/form-data ContentType.
type PostApiV1AvatarsMultipartRequestBody PostApiV1AvatarsMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/avatars)
	PostApiV1Avatars(ctx echo.Context, params PostApiV1AvatarsParams) error

	// (DELETE /api/v1/avatars/{id})
	DeleteApiV1AvatarsId(ctx echo.Context, id openapi_types.UUID, params DeleteApiV1AvatarsIdParams) error

	// (GET /api/v1/avatars/{id})
	GetApiV1AvatarsId(ctx echo.Context, id openapi_types.UUID, params GetApiV1AvatarsIdParams) error

	// (GET /api/v1/avatars/{id}/metadata)
	GetApiV1AvatarsIdMetadata(ctx echo.Context, id openapi_types.UUID) error

	// (GET /health)
	GetHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostApiV1Avatars converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1Avatars(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiV1AvatarsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1Avatars(ctx, params)
	return err
}

// DeleteApiV1AvatarsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1AvatarsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiV1AvatarsIdParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1AvatarsId(ctx, id, params)
	return err
}

// GetApiV1AvatarsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1AvatarsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1AvatarsIdParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1AvatarsId(ctx, id, params)
	return err
}

// GetApiV1AvatarsIdMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1AvatarsIdMetadata(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1AvatarsIdMetadata(ctx, id)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/avatars", wrapper.PostApiV1Avatars)
	router.DELETE(baseURL+"/api/v1/avatars/:id", wrapper.DeleteApiV1AvatarsId)
	router.GET(baseURL+"/api/v1/avatars/:id", wrapper.GetApiV1AvatarsId)
	router.GET(baseURL+"/api/v1/avatars/:id/metadata", wrapper.GetApiV1AvatarsIdMetadata)
	router.GET(baseURL+"/health", wrapper.GetHealth)

}

type PostApiV1AvatarsRequestObject struct {
	Params PostApiV1AvatarsParams
	Body   *multipart.Reader
}

type PostApiV1AvatarsResponseObject interface {
	VisitPostApiV1AvatarsResponse(w http.ResponseWriter) error
}

type PostApiV1Avatars201JSONResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Status    string             `json:"status"`
	Url       string             `json:"url"`
	UserId    string             `json:"user_id"`
}

func (response PostApiV1Avatars201JSONResponse) VisitPostApiV1AvatarsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Avatars400JSONResponse struct {
	Details string `json:"details"`
	Error   string `json:"error"`
}

func (response PostApiV1Avatars400JSONResponse) VisitPostApiV1AvatarsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Avatars413JSONResponse struct {
	Error   string `json:"error"`
	MaxSize string `json:"max_size"`
}

func (response PostApiV1Avatars413JSONResponse) VisitPostApiV1AvatarsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1AvatarsIdRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params DeleteApiV1AvatarsIdParams
}

type DeleteApiV1AvatarsIdResponseObject interface {
	VisitDeleteApiV1AvatarsIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1AvatarsId200Response struct {
}

func (response DeleteApiV1AvatarsId200Response) VisitDeleteApiV1AvatarsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteApiV1AvatarsId403JSONResponse struct {
	Details string `json:"details"`
	Error   string `json:"error"`
}

func (response DeleteApiV1AvatarsId403JSONResponse) VisitDeleteApiV1AvatarsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1AvatarsIdRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetApiV1AvatarsIdParams
}

type GetApiV1AvatarsIdResponseObject interface {
	VisitGetApiV1AvatarsIdResponse(w http.ResponseWriter) error
}

type GetApiV1AvatarsId200MultipartResponse func(writer *multipart.Writer) error

func (response GetApiV1AvatarsId200MultipartResponse) VisitGetApiV1AvatarsIdResponse(w http.ResponseWriter) error {
	writer := multipart.NewWriter(w)
	w.Header().Set("Content-Type", writer.FormDataContentType())
	w.WriteHeader(200)

	defer writer.Close()
	return response(writer)
}

type GetApiV1AvatarsId404JSONResponse struct {
	Error string `json:"error"`
}

func (response GetApiV1AvatarsId404JSONResponse) VisitGetApiV1AvatarsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1AvatarsIdMetadataRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetApiV1AvatarsIdMetadataResponseObject interface {
	VisitGetApiV1AvatarsIdMetadataResponse(w http.ResponseWriter) error
}

type GetApiV1AvatarsIdMetadata200JSONResponse struct {
	CreatedAt  time.Time `json:"created_at"`
	Dimensions struct {
		Height int `json:"height"`
		Width  int `json:"width"`
	} `json:"dimensions"`
	FileName   string             `json:"file_name"`
	Id         openapi_types.UUID `json:"id"`
	MimeType   string             `json:"mime_type"`
	Size       int                `json:"size"`
	Thumbnails *[]struct {
		Size string `json:"size"`
		Url  string `json:"url"`
	} `json:"thumbnails,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
	UserId    string    `json:"user_id"`
}

func (response GetApiV1AvatarsIdMetadata200JSONResponse) VisitGetApiV1AvatarsIdMetadataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1AvatarsIdMetadata404JSONResponse struct {
	Error string `json:"error"`
}

func (response GetApiV1AvatarsIdMetadata404JSONResponse) VisitGetApiV1AvatarsIdMetadataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Broker string `json:"broker"`
	Db     string `json:"db"`
	S3     string `json:"s3"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/avatars)
	PostApiV1Avatars(ctx context.Context, request PostApiV1AvatarsRequestObject) (PostApiV1AvatarsResponseObject, error)

	// (DELETE /api/v1/avatars/{id})
	DeleteApiV1AvatarsId(ctx context.Context, request DeleteApiV1AvatarsIdRequestObject) (DeleteApiV1AvatarsIdResponseObject, error)

	// (GET /api/v1/avatars/{id})
	GetApiV1AvatarsId(ctx context.Context, request GetApiV1AvatarsIdRequestObject) (GetApiV1AvatarsIdResponseObject, error)

	// (GET /api/v1/avatars/{id}/metadata)
	GetApiV1AvatarsIdMetadata(ctx context.Context, request GetApiV1AvatarsIdMetadataRequestObject) (GetApiV1AvatarsIdMetadataResponseObject, error)

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostApiV1Avatars operation middleware
func (sh *strictHandler) PostApiV1Avatars(ctx echo.Context, params PostApiV1AvatarsParams) error {
	var request PostApiV1AvatarsRequestObject

	request.Params = params

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Avatars(ctx.Request().Context(), request.(PostApiV1AvatarsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Avatars")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostApiV1AvatarsResponseObject); ok {
		return validResponse.VisitPostApiV1AvatarsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteApiV1AvatarsId operation middleware
func (sh *strictHandler) DeleteApiV1AvatarsId(ctx echo.Context, id openapi_types.UUID, params DeleteApiV1AvatarsIdParams) error {
	var request DeleteApiV1AvatarsIdRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1AvatarsId(ctx.Request().Context(), request.(DeleteApiV1AvatarsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1AvatarsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteApiV1AvatarsIdResponseObject); ok {
		return validResponse.VisitDeleteApiV1AvatarsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetApiV1AvatarsId operation middleware
func (sh *strictHandler) GetApiV1AvatarsId(ctx echo.Context, id openapi_types.UUID, params GetApiV1AvatarsIdParams) error {
	var request GetApiV1AvatarsIdRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AvatarsId(ctx.Request().Context(), request.(GetApiV1AvatarsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AvatarsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiV1AvatarsIdResponseObject); ok {
		return validResponse.VisitGetApiV1AvatarsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetApiV1AvatarsIdMetadata operation middleware
func (sh *strictHandler) GetApiV1AvatarsIdMetadata(ctx echo.Context, id openapi_types.UUID) error {
	var request GetApiV1AvatarsIdMetadataRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AvatarsIdMetadata(ctx.Request().Context(), request.(GetApiV1AvatarsIdMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AvatarsIdMetadata")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiV1AvatarsIdMetadataResponseObject); ok {
		return validResponse.VisitGetApiV1AvatarsIdMetadataResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
