{{- if .Values.worker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-worker
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.env.ENV | quote }}
  APP_NAME: {{ printf "%s-worker" .Values.env.APP_NAME | quote }}
  APP_S3_ADDR: {{ .Values.env.APP_S3_ADDR | quote }}
  APP_S3_BUCKET_NAME: {{ .Values.env.APP_S3_BUCKET_NAME | quote }}
  APP_KAFKA_ADDR: {{ .Values.env.APP_KAFKA_ADDR | quote }}
  APP_KAFKA_TOPIC: {{ .Values.env.APP_KAFKA_TOPIC | quote }}
  OTEL_SERVICE_NAME: {{ printf "%s-worker" .Values.env.OTEL_SERVICE_NAME | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
  OTEL_EXPORTER_OTLP_INSECURE: {{ .Values.env.OTEL_EXPORTER_OTLP_INSECURE | quote }}
{{- end }}
