// Code generated by MockGen. DO NOT EDIT.
// Source: internal/feature/avatar/domain/use_case_delete_avatar.go
//
// Generated by this command:
//
//	mockgen -source=internal/feature/avatar/domain/use_case_delete_avatar.go -destination=internal/feature/avatar/domain/mock/mock_delete_avatar_repos.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "goph-profile/internal/feature/avatar/domain/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteAvatarRepo is a mock of DeleteAvatarRepo interface.
type MockDeleteAvatarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteAvatarRepoMockRecorder
	isgomock struct{}
}

// MockDeleteAvatarRepoMockRecorder is the mock recorder for MockDeleteAvatarRepo.
type MockDeleteAvatarRepoMockRecorder struct {
	mock *MockDeleteAvatarRepo
}

// NewMockDeleteAvatarRepo creates a new mock instance.
func NewMockDeleteAvatarRepo(ctrl *gomock.Controller) *MockDeleteAvatarRepo {
	mock := &MockDeleteAvatarRepo{ctrl: ctrl}
	mock.recorder = &MockDeleteAvatarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteAvatarRepo) EXPECT() *MockDeleteAvatarRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleteAvatarRepo) Delete(ctx context.Context, userID string, avatarID uuid.UUID) (model.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, avatarID)
	ret0, _ := ret[0].(model.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleteAvatarRepoMockRecorder) Delete(ctx, userID, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleteAvatarRepo)(nil).Delete), ctx, userID, avatarID)
}

// MockDeleteAvatarEventDispatcher is a mock of DeleteAvatarEventDispatcher interface.
type MockDeleteAvatarEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteAvatarEventDispatcherMockRecorder
	isgomock struct{}
}

// MockDeleteAvatarEventDispatcherMockRecorder is the mock recorder for MockDeleteAvatarEventDispatcher.
type MockDeleteAvatarEventDispatcherMockRecorder struct {
	mock *MockDeleteAvatarEventDispatcher
}

// NewMockDeleteAvatarEventDispatcher creates a new mock instance.
func NewMockDeleteAvatarEventDispatcher(ctrl *gomock.Controller) *MockDeleteAvatarEventDispatcher {
	mock := &MockDeleteAvatarEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockDeleteAvatarEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteAvatarEventDispatcher) EXPECT() *MockDeleteAvatarEventDispatcherMockRecorder {
	return m.recorder
}

// AvatarDeleted mocks base method.
func (m *MockDeleteAvatarEventDispatcher) AvatarDeleted(ctx context.Context, avatarID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarDeleted", ctx, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AvatarDeleted indicates an expected call of AvatarDeleted.
func (mr *MockDeleteAvatarEventDispatcherMockRecorder) AvatarDeleted(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarDeleted", reflect.TypeOf((*MockDeleteAvatarEventDispatcher)(nil).AvatarDeleted), ctx, avatarID)
}
