// Code generated by MockGen. DO NOT EDIT.
// Source: internal/feature/avatar/domain/use_case_upload_avatar.go
//
// Generated by this command:
//
//	mockgen -source=internal/feature/avatar/domain/use_case_upload_avatar.go -destination=internal/feature/avatar/domain/mock/mock_upload_avatar_repos.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "goph-profile/internal/feature/avatar/domain/model"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadAvatarMetadataRepo is a mock of UploadAvatarMetadataRepo interface.
type MockUploadAvatarMetadataRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUploadAvatarMetadataRepoMockRecorder
	isgomock struct{}
}

// MockUploadAvatarMetadataRepoMockRecorder is the mock recorder for MockUploadAvatarMetadataRepo.
type MockUploadAvatarMetadataRepoMockRecorder struct {
	mock *MockUploadAvatarMetadataRepo
}

// NewMockUploadAvatarMetadataRepo creates a new mock instance.
func NewMockUploadAvatarMetadataRepo(ctrl *gomock.Controller) *MockUploadAvatarMetadataRepo {
	mock := &MockUploadAvatarMetadataRepo{ctrl: ctrl}
	mock.recorder = &MockUploadAvatarMetadataRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadAvatarMetadataRepo) EXPECT() *MockUploadAvatarMetadataRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUploadAvatarMetadataRepo) Add(ctx context.Context, avatarID uuid.UUID, userID, fileName string, mimeType model.FormatType, width, height, size int, s3key string) (model.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, avatarID, userID, fileName, mimeType, width, height, size, s3key)
	ret0, _ := ret[0].(model.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockUploadAvatarMetadataRepoMockRecorder) Add(ctx, avatarID, userID, fileName, mimeType, width, height, size, s3key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUploadAvatarMetadataRepo)(nil).Add), ctx, avatarID, userID, fileName, mimeType, width, height, size, s3key)
}

// MockUploadAvatarRepo is a mock of UploadAvatarRepo interface.
type MockUploadAvatarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUploadAvatarRepoMockRecorder
	isgomock struct{}
}

// MockUploadAvatarRepoMockRecorder is the mock recorder for MockUploadAvatarRepo.
type MockUploadAvatarRepoMockRecorder struct {
	mock *MockUploadAvatarRepo
}

// NewMockUploadAvatarRepo creates a new mock instance.
func NewMockUploadAvatarRepo(ctrl *gomock.Controller) *MockUploadAvatarRepo {
	mock := &MockUploadAvatarRepo{ctrl: ctrl}
	mock.recorder = &MockUploadAvatarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadAvatarRepo) EXPECT() *MockUploadAvatarRepoMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploadAvatarRepo) Upload(ctx context.Context, name, format string, size int, img io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, name, format, size, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUploadAvatarRepoMockRecorder) Upload(ctx, name, format, size, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploadAvatarRepo)(nil).Upload), ctx, name, format, size, img)
}

// MockUploadAvatarEventDispatcher is a mock of UploadAvatarEventDispatcher interface.
type MockUploadAvatarEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockUploadAvatarEventDispatcherMockRecorder
	isgomock struct{}
}

// MockUploadAvatarEventDispatcherMockRecorder is the mock recorder for MockUploadAvatarEventDispatcher.
type MockUploadAvatarEventDispatcherMockRecorder struct {
	mock *MockUploadAvatarEventDispatcher
}

// NewMockUploadAvatarEventDispatcher creates a new mock instance.
func NewMockUploadAvatarEventDispatcher(ctrl *gomock.Controller) *MockUploadAvatarEventDispatcher {
	mock := &MockUploadAvatarEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockUploadAvatarEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadAvatarEventDispatcher) EXPECT() *MockUploadAvatarEventDispatcherMockRecorder {
	return m.recorder
}

// AvatarUploaded mocks base method.
func (m *MockUploadAvatarEventDispatcher) AvatarUploaded(ctx context.Context, avatarID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarUploaded", ctx, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AvatarUploaded indicates an expected call of AvatarUploaded.
func (mr *MockUploadAvatarEventDispatcherMockRecorder) AvatarUploaded(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarUploaded", reflect.TypeOf((*MockUploadAvatarEventDispatcher)(nil).AvatarUploaded), ctx, avatarID)
}
