// Code generated by MockGen. DO NOT EDIT.
// Source: internal/feature/avatar/domain/use_case_get_avatar.go
//
// Generated by this command:
//
//	mockgen -source=internal/feature/avatar/domain/use_case_get_avatar.go -destination=internal/feature/avatar/domain/mock/mock_get_avatar_repos.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "goph-profile/internal/feature/avatar/domain/model"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetAvatarKeyRepo is a mock of GetAvatarKeyRepo interface.
type MockGetAvatarKeyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGetAvatarKeyRepoMockRecorder
	isgomock struct{}
}

// MockGetAvatarKeyRepoMockRecorder is the mock recorder for MockGetAvatarKeyRepo.
type MockGetAvatarKeyRepoMockRecorder struct {
	mock *MockGetAvatarKeyRepo
}

// NewMockGetAvatarKeyRepo creates a new mock instance.
func NewMockGetAvatarKeyRepo(ctrl *gomock.Controller) *MockGetAvatarKeyRepo {
	mock := &MockGetAvatarKeyRepo{ctrl: ctrl}
	mock.recorder = &MockGetAvatarKeyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAvatarKeyRepo) EXPECT() *MockGetAvatarKeyRepoMockRecorder {
	return m.recorder
}

// Avatar mocks base method.
func (m *MockGetAvatarKeyRepo) Avatar(ctx context.Context, avatarID uuid.UUID, format *model.FormatType, aspectRatio *model.AspectRatio) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Avatar", ctx, avatarID, format, aspectRatio)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Avatar indicates an expected call of Avatar.
func (mr *MockGetAvatarKeyRepoMockRecorder) Avatar(ctx, avatarID, format, aspectRatio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Avatar", reflect.TypeOf((*MockGetAvatarKeyRepo)(nil).Avatar), ctx, avatarID, format, aspectRatio)
}

// MockFetchAvatarRepo is a mock of FetchAvatarRepo interface.
type MockFetchAvatarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFetchAvatarRepoMockRecorder
	isgomock struct{}
}

// MockFetchAvatarRepoMockRecorder is the mock recorder for MockFetchAvatarRepo.
type MockFetchAvatarRepoMockRecorder struct {
	mock *MockFetchAvatarRepo
}

// NewMockFetchAvatarRepo creates a new mock instance.
func NewMockFetchAvatarRepo(ctrl *gomock.Controller) *MockFetchAvatarRepo {
	mock := &MockFetchAvatarRepo{ctrl: ctrl}
	mock.recorder = &MockFetchAvatarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchAvatarRepo) EXPECT() *MockFetchAvatarRepoMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockFetchAvatarRepo) Fetch(ctx context.Context, name string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, name)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockFetchAvatarRepoMockRecorder) Fetch(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockFetchAvatarRepo)(nil).Fetch), ctx, name)
}
