// Code generated by MockGen. DO NOT EDIT.
// Source: internal/feature/avatar/domain/use_case_get_avatar_metadata.go
//
// Generated by this command:
//
//	mockgen -source=internal/feature/avatar/domain/use_case_get_avatar_metadata.go -destination=internal/feature/avatar/domain/mock/mock_get_avatar_metadata_repos.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "goph-profile/internal/feature/avatar/domain/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetAvatarMetadataRepo is a mock of GetAvatarMetadataRepo interface.
type MockGetAvatarMetadataRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGetAvatarMetadataRepoMockRecorder
	isgomock struct{}
}

// MockGetAvatarMetadataRepoMockRecorder is the mock recorder for MockGetAvatarMetadataRepo.
type MockGetAvatarMetadataRepoMockRecorder struct {
	mock *MockGetAvatarMetadataRepo
}

// NewMockGetAvatarMetadataRepo creates a new mock instance.
func NewMockGetAvatarMetadataRepo(ctrl *gomock.Controller) *MockGetAvatarMetadataRepo {
	mock := &MockGetAvatarMetadataRepo{ctrl: ctrl}
	mock.recorder = &MockGetAvatarMetadataRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAvatarMetadataRepo) EXPECT() *MockGetAvatarMetadataRepoMockRecorder {
	return m.recorder
}

// Metadata mocks base method.
func (m *MockGetAvatarMetadataRepo) Metadata(ctx context.Context, avatarID uuid.UUID) (model.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx, avatarID)
	ret0, _ := ret[0].(model.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockGetAvatarMetadataRepoMockRecorder) Metadata(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockGetAvatarMetadataRepo)(nil).Metadata), ctx, avatarID)
}
